# exception with zeroerror

try :
    print(10/0)
except:
    print("exception occur")
